### ISSUE TITLE
Application Moderator

### ISSUE THREAD

**Issue by BenzeiGames** [CCEU/IssueTracker#25]
1. General Information

Minecraft username: 
„BenzeiGames“
Minecraft-UUID: 
Full: 84ba7e0e-28c5-45e2-8923-1adca4d4e6a5
Timezone: 
MEZ (UTC+1)
Age:
16 (29th August 2001)
Do you have access to TeamSpeak and a working microphone?
Yes, but I think the whole CCEU-Team know that. 
Do you have the ability to record minecraft video?
Yes, I have the ability to record every kind of video.
What is your current Rank on CCEU?
My current rank is Supporter.
Gaming Twitter link (If you have one)::
No, sry.
Are you multilingual? (Fluent in multiple languages. Not just learning one.)
I have a good feeling for language, but im not multilingual.
Do you speak German?
Ich denke mal.

2. Where are you most active on the CCEU Network?

What game types do you play?
I like every kind of game types.
Do you actively use the forums?
No, because the Forum doesn’t exists. 
Do you enjoy being in game more?
No.
Etc..?
3. How much time do you have to contribute to the role?
I can’t say that exactly, but I think 1-2 hours daily.
4. Have you ever been banned or punished on any server? If so, please include details...
Not really.
5. SCENARIO: Suppose it's your first week of being a Moderator and you mute a well-known player. Their mates start spamming your twitter calling you a bad Moderator and telling you to unmute them. What would you do?	
I would ignore the mates. When the mates doesn’t stop spamming, I would punish them too.
6. Tell us about one of your best moments on the CCEU server
My best moment was the First-connect on Creeper-Craft in the Year 2012/13, because this server was my first game server I’ve ever entered. 

7. Tell us about a time you made a mistake within the last year? How did you deal with it? What did you learn? (Nothing related to gaming please)
I’m a human. I do a lot of mistakes, but I try to delimit them. I can’t list that, because they are many mistakes. I learned from every Mistake. My slogan for Mistakes: “Don’t Fear Failure”
8. If you have any, what hobbies or activities are you involved in outside of Minecraft?
My hobbies are model building, photography, music and martial Arts.

9. Do you have any previous server moderation or leadership experience?
Ok, diesen Part mache ich nun auf Deutsch, da er sehr umfangreich und detailliert werden soll.
**Lenosia.net**
In diesem Kleingewerbe habe ich die Rolle als Social-Media Manager und Servertechniker in den Fachbereichen Server-Status, Teamspeak und Gameservern bekommen. Ich lernte von Monat zu Monat, was Teamfähigkeit und Konfliktfähigkeit bedeuteten. Für mich waren diese zwei Eigenschaften nur Wörter, mit denen ich nichts anfangen konnte, aber nach der Lenosia Zeit war mir bewusst, wovon ich rede, wenn ich sage, dass ich Konfliktfähig und Teamfähig in einer ausgeprägten Form bin. 
Ich denke ich werde diese zwei Eigenschaften für ein Amt als Moderator brauchen.

**Battlenetwork Europa (BNE)**
Dieses Projekt war groß geplant, es sollte ein Server-Hosting Projekt werden, was leider durch mangel der Techniker nach 2 Monaten gescheitert ist. In diesem Unternehmen habe ich die Rolle als Leiter des Supports gespielt, wodurch sich meine Teamfähigkeit und Konfliktfähigkeit nochmal ausgeprägt haben.
 10. SCENARIO: "You come home from school/work and have ton of homework/work to do, you think to yourself I'll just take a 5 minute break before I start and get on CCEU. The next thing you know 2 hours have passed and you've been on the server all that time." Does this scenario sound familiar to you?
No, first the Work, then the leisure.
11. SCENARIO: You're in a busy lobby as a moderator, questions are flying at you rapidly, you can just about keep up. You're getting messaged by 2 different players both asking you to get them a moderator for a hacker, someone then pokes you on TeamSpeak telling you that there is someone blasting music in their channel. What do you do?
First I would check the Problem in the Teamspeak Server. After that I would have a look at the Hacker.
  
12. Have you made any previous applications, if so how many and what is the date of your last one?
No, sry.
13. Anything else we should know?
Nope.

**Comment by CCCoderDE** [comment]
accepted.
