### ISSUE TITLE
!Info an ADMINS! Bitte nochmal mit Relaxo sprechen, hat sich als Team Member interessiert

### ISSUE THREAD

**Issue by BenzeiGames** [CCEU/IssueTracker#26]
Daten zu Ihm:
Name: Relaxo
UID: IXfa8cjilQJOqZxLsim/CNqeKN8=
ID: 68
DBID: 12482
TalkPower: 0
Icon ID: 0

Alter: 14

**Comment by CCCoderDE** [comment]
rejected.

reason: only 12 connects
