### ISSUE TITLE
Bewerbung als Moderator

### ISSUE THREAD

**Issue by PoggleLP** [CCEU/IssueTracker#28]
1. General Information
Your username: PoggleLP
Your Teamspeak-UniqueID (Please look it up!): X7ktAadWawOUcmDzeG3Gxhk+lhw= 
Timezone: MEZ (UTC+1)
Age (Note: You must be 16 or over to apply): 16
Do you have the ability to record sound/video?: Yes, i can record sound and video data
What is your current rank on CCEU?: Explorer
Social-Media links (Twitter, Twitch, YouTube, etc.) (optional): 
Are you multilingual? (Fluent in multiple languages. Not just learning one.): I can speak english and german.
Do you speak German?: Yes, i can speak german.
2. Where are you most active on the CCEU Network?: I am playing games with friends or i talk with then.
What games do you play?: Ego Shooter, Singleplayer
Do you have a clan-channel on CCEU?: Yes im in the Clan CC.
Etc..?: No
3. How much time do you have to contribute to the role?: i am the most of the week on the Teamspeak.
4. Have you ever been banned or punished on any server? If so, please include details...: I was banned from the moderator "Benzei", because i turn on loud Sound on my soundboard and that more times.
5. SCENARIO: Suppose it's your first week of being a Moderator and you ban a well-known user. Their mates start spamming your twitter calling you a bad Moderator and telling you to unban them. What would you do?: I would ignore them and go to the admin and tell it them.
6. Tell us about one of your best moments on the CCEU Server: The best Moment was, where i become to member af the CC clan and i can Play with the admin and the moderator.
7. Tell us about a time you made a mistake within the last year? How did you deal with it? What did you learn? (Nothing related to gaming please): I got a 4 in english on my certificate and i solved it, by learn more and get better marks.I learn with that, that i make something for the School.
8. If you have any, what hobbies or activities are you involved in outside of Gaming?: I like it to see my friends. I Play also sometimes soccer with them.
9. Do you have any previous server moderation or leadership experience?: No i dont have any experience.
If so explain what role you played, what skills/experiences you picked up and how this will help you in your role as a moderator.: /
10. SCENARIO: "You come home from school/work and have ton of homework/work to do, you think to yourself I'll just take a 5 minute break before I start and get on CCEU. The next thing you know 2 hours have passed and you've been on the server all that time." Does this scenario sound familiar to you?": Yes, i often play games on the CCEU Server, but i had to do many homeworks.
11. SCENARIO: You're in a busy channel as a moderator, questions are flying at you rapidly, you can just about keep up. You're getting messaged by 2 different players both asking you to get them a moderator for a spammer, someone then pokes you on TeamSpeak telling you that there is someone blasting music in their channel. What do you do?: I move the two Players in my channal and talk to them and search a other moderator and talk to them that he go to the Music Player. If there is no moderator i solve first one Problem and then the other.
12. Have you made any previous applications (only CCEU), if so how many and what is the date of your last one?. No, i dont make anything of that.
13. Anything else we should know?: I Play many time on this teamspeak and i want to help the Admin and the Players on that Server.

**Comment by CCCoderDE** [comment]
The User will get [Complaints Officer].
