### ISSUE TITLE
Bewerbung als Moderator

### ISSUE THREAD

**Issue by zzbbgg** [CCEU/IssueTracker#29]
1. General Information

    Your username:Aldi Penner
    Your Teamspeak-UniqueID (Please look it up!):wzMwaEFmEC/vpbQDE3IOGCljrw4=
    Timezone:MEZ (UTC+1)
    Age (Note: You must be 16 or over to apply):16
    Do you have the ability to record sound/video?: Yes, my computer can record.
    What is your current rank on CCEU?: Explorer
    Social-Media links (Twitter, Twitch, YouTube, etc.) (optional):
    Are you multilingual? (Fluent in multiple languages. Not just learning one.): I can speak german and a      bit english
    Do you speak German?: Yes of course.

2. Where are you most active on the CCEU Network?

    What games do you play?: I play shooter, singelplayer and survival games.
    Do you have a clan-channel on CCEU?: In the CC clan.
    Etc..?

3. How much time do you have to contribute to the role?: I am the most days of the Teamspeak.
4. Have you ever been banned or punished on any server? If so, please include details... : Yes from Benzei of the Teamspeak cceu.eu because i have lot little reports.
5. SCENARIO: Suppose it's your first week of being a Moderator and you ban a well-known user. Their mates start spamming your twitter calling you a bad Moderator and telling you to unban them. What would you do?: I ignor they and ask when it is to lot spamming the Admin.
6. Tell us about one of your best moments on the CCEU server.: Find new members to play games and join the CC clan?
7. Tell us about a time you made a mistake within the last year? How did you deal with it? What did you learn? (Nothing related to gaming please): I don´t do my homework  and became a bad note and i ask my teacher to became a better note.
8. If you have any, what hobbies or activities are you involved in outside of Gaming?: I do Judo, go to table tennis ani i am in the fishing society.
9. Do you have any previous server moderation or leadership experience?No i am not.

    If so explain what role you played, what skills/experiences you picked up and how this will help you in your role as a moderator.: I never was moderator.

10. SCENARIO: "You come home from school/work and have ton of homework/work to do, you think to yourself I'll just take a 5 minute break before I start and get on CCEU. The next thing you know 2 hours have passed and you've been on the server all that time." Does this scenario sound familiar to you?:Yes i am lt of the cceu.eu server and at gaming anibody forgett the time.
11. SCENARIO: You're in a busy channel as a moderator, questions are flying at you rapidly, you can just about keep up. You're getting messaged by 2 different players both asking you to get them a moderator for a spammer, someone then pokes you on TeamSpeak telling you that there is someone blasting music in their channel. What do you do?: I move the tow in one chanel and sat that they should not do that.
12. Have you made any previous applications (only CCEU), if so how many and what is the date of your last one?: No i don´t have it.
13. Anything else we should know?:I am lot of the time on the Teamspeak "cceu.eu". I hope you enjoy!

**Comment by BenzeiGames** [comment]
Clarification to Point 4;
You got a lot of Reports for C5 (Do not sing, play music or any other annoying sounds) and C3 (Do not switch Channels too fast). I would not say "a lot little reports"

**Comment by CCCoderDE** [comment]
The User will get [Complaints Officer].
