### ISSUE TITLE
Teamspeak-Bot Features

### ISSUE THREAD

**Issue by CCCoderDE** [CCEU/IssueTracker#31]
Final Feature-List:

- [x] Support-Channel Poke
- [ ] Illegal Nickname Kick
- [ ] No Recording
- [ ] LastSeen
- [ ] AFK-Mover

**Comment by BenzeiGames** [comment]
-Schutz vor Aufnahmen-
Bestraft Clients wenn sie (versuchen) eine Aufnahme (zu) tätigen.

**Comment by BenzeiGames** [comment]
-Eine Art Log für User-
Ein Chat-Befehl an den Bot, um den letzten Online Zeitpunkt und Aufenthalt eines Clients zu ermitteln.

**Comment by BenzeiGames** [comment]
-Automatisches Zurückmoven nach timeout-
Selbsterklärend.

**Comment by BenzeiGames** [comment]
-Unerlaubte Zeichen/Wörter-
Man wird angepokt/gekickt, wenn ein Wort/zeichen zutrifft.

**Comment by BenzeiGames** [comment]
-Move bei Mute-
Wenn man sich mutet/ Status auf abwesend setzt, wird man gekickt
